set_property IOSTANDARD LVCMOS33 [get_ports *]

set_property PACKAGE_PIN V10 [get_ports {a[2]}]
set_property PACKAGE_PIN U11 [get_ports {a[1]}]
set_property PACKAGE_PIN U12 [get_ports {a[0]}]
set_property PACKAGE_PIN J15 [get_ports {d[0]}]
set_property PACKAGE_PIN L16 [get_ports {d[1]}]
set_property PACKAGE_PIN M13 [get_ports {d[2]}]
set_property PACKAGE_PIN R15 [get_ports {d[3]}]
set_property PACKAGE_PIN R17 [get_ports {d[4]}]
set_property PACKAGE_PIN T18 [get_ports {d[5]}]
set_property PACKAGE_PIN U18 [get_ports {d[6]}]
set_property PACKAGE_PIN R13 [get_ports {d[7]}]
set_property PACKAGE_PIN N17 [get_ports en_n]
set_property PACKAGE_PIN K15 [get_ports y]
set_property PACKAGE_PIN H17 [get_ports y_n]
