set_property IOSTANDARD LVCMOS33 [get_ports *]

set_property PACKAGE_PIN V10 [get_ports {a_n[2]}]
set_property PACKAGE_PIN U11 [get_ports {a_n[1]}]
set_property PACKAGE_PIN U12 [get_ports {a_n[0]}]
set_property PACKAGE_PIN H17 [get_ports {y_n[0]}]
set_property PACKAGE_PIN K15 [get_ports {y_n[1]}]
set_property PACKAGE_PIN J13 [get_ports {y_n[2]}]
set_property PACKAGE_PIN N14 [get_ports {y_n[3]}]
set_property PACKAGE_PIN R18 [get_ports {y_n[4]}]
set_property PACKAGE_PIN V17 [get_ports {y_n[5]}]
set_property PACKAGE_PIN U17 [get_ports {y_n[6]}]
set_property PACKAGE_PIN U16 [get_ports {y_n[7]}]
set_property PACKAGE_PIN M13 [get_ports s_a]
set_property PACKAGE_PIN L16 [get_ports s_b]
set_property PACKAGE_PIN J15 [get_ports s_c]
